---
blank_issues_enabled: false
contact_links:
  - name: Ask a question (GitHub Discussions)
    url: https://github.com/apache/netbeans/discussions/
    about: Ask a question or request support for using Apache NetBeans.
  - name: Mailing lists
    url: https://netbeans.apache.org/community/mailing-lists
    about: Subscribe to the users, dev or announce mailing lists for Apache NetBeans.
