# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: NetBeans Dependency Checks

on:
#  pull_request:
  # Allows you to run this workflow manually from the Actions tab in GitHub UI
  workflow_dispatch:

# cancel other workflow run in the same head-base group if it exists
concurrency: 
  group: dep-checker-${{ github.head_ref || github.run_id }}-${{ github.base_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  base-build:
    name: Check Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

      - name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: false
          show-progress: false

      - name: Check Dependencies
        run: |
          mvn -q dependency:copy -Dartifact=org.apache.maven.indexer:search-backend-smo:7.1.1 -DoutputDirectory=./lib
          mvn -q dependency:copy -Dartifact=org.apache.maven.indexer:search-api:7.1.1         -DoutputDirectory=./lib
          mvn -q dependency:copy -Dartifact=com.google.code.gson:gson:2.10.1                  -DoutputDirectory=./lib
          mvn -q dependency:copy -Dartifact=org.apache.maven:maven-artifact:3.9.6             -DoutputDirectory=./lib
          echo "<pre>" >> $GITHUB_STEP_SUMMARY
          $JAVA_HOME_21_X64/bin/java --enable-preview --source 21 -cp "lib/*" .github/scripts/BinariesListUpdates.java ./ | tee -a $GITHUB_STEP_SUMMARY
          echo "</pre>" >> $GITHUB_STEP_SUMMARY
          rm -Rf lib
